export default {
  ME2001: "HTTP GET method-оор өгөгдөл хүлээн авах боломжгүй'",
  ME2002: "XML өгөгдөл алга байна'",
  ME2003: "X-Username толгойн мэдээлэл алга байна'",
  ME2004: "X-Signature толгойн мэдээлэл алга байна'",
  ME2005: "userName буруу'",
  ME2006: "Нууц үг буруу байна'",
  ME2007: "customers таагийн Action нь байхгүй байна.'",
  ME2008: "customers таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME2009: "o_c_customer_information таагийн Action нь байхгүй байна.'",
  ME2010: "o_c_customer_information таагийн Action-ны утга нь жагсаалтанд байхгүй байна.'",
  ME2011: "o_c_customer_information-ны customercode тааг байхгүй байна.'",
  ME2012: "o_c_customer_information-ны customercode таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2013: "o_c_customer_information-ны loandescription таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2014: "o_c_customer_information-ны bankcode тааг байхгүй байна.'",
  ME2015: "o_c_customer_information-ны bankcode таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2016: "o_c_customer_information-ны branchcode тааг байхгүй байна.'",
  ME2017: "o_c_customer_information-ны branchcode таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2018: "o_c_customer_information-ны isorganization таагийн байхгүй байна.'",
  ME2019: "o_c_customer_information-ны isorganization таагийн утга 0 эсвэл 1 биш байна.'",
  ME2020: "o_c_customer_information-ны customername тааг байхгүй байна.'",
  ME2021: "o_c_customer_information-ны customername таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2022: "o_c_customer_information-ны lastname таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2023: "o_c_customer_information-ны isforeign тааг байхгүй байна.'",
  ME2024: "o_c_customer_information-ны isforeign таагийн утга 0 эсвэл 1 биш байна.'",
  ME2025: "o_c_customer_information-ны birthdate таагийн оруулсан утгын формат буруу байна.'",
  ME2026: "o_c_customer_information таагийн zipcode байхгүй байна.'",
  ME2027: "o_c_customer_information-ны zipcode таагийн утга буруу байна.'",
  ME2028: "o_c_customer_information-ны address тааг байхгүй байна.'",
  ME2029: "o_c_customer_information-ны address таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2030: "o_c_customer_information-ны registerno тааг байхгүй байна.'",
  ME2031: "o_c_customer_information-ны registernо таагийн утга буруу форматтай байна.'",
  ME2032: "o_c_customer_information-ны stateregister_passportno таагийн утга буруу форматтай байна.'",
  ME2033: "o_c_customer_information-ны numofemployee таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2034: "o_c_customer_information-ны numofemployee таагийн утга бүхэл тоо биш байна.'",
  ME2035: "o_c_customer_information-ны familynumofmembers тааг-д буруу утга оруулсан байна.'",
  ME2036: "o_c_customer_information-ны familynumofmembers таагийн утга бүхэл тоо биш байна.'",
  ME2037: "o_c_customer_information-ны familynumofunemployed таагд буруу утга оруулсан байна.'",
  ME2038: "o_c_customer_information-ны familynumofunemployed таагийн утга бүхэл тоо биш байна.'",
  ME2039: "o_c_customer_information-ны job таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2040: "o_c_customer_information-ны occupation таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2041: "o_c_customer_information-ны occupation таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2042: "o_c_customer_information-ны fitchrating таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2043: "o_c_customer_information-ны fitchrating таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2044: "o_c_customer_information-ны sandp_rating таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2045: "o_c_customer_information-ны sandp_rating таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2046: "o_c_customer_information-ны moodysrating таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2047: "o_c_customer_information-ны moodysrating таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2048: "o_c_customer_information-ны сompanytypecode тааг байхгүй байна.'",
  ME2049: "o_c_customer_information-ны сompanytypecode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2050: "o_c_customer_information-ны сompanytypecode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2051: "o_c_customer_information-ны рresident_family_firstname тааг байхгүй байна.'",
  ME2052: "o_c_customer_information-ны рresident_family_firstname таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2053: "o_c_customer_information-ны рresident_family_lastname тааг байхгүй байна.'",
  ME2054: "o_c_customer_information-ны рresident_family_lastname таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2055: "o_c_customer_information-ны рresident_family_isforeign тааг байхгүй байна.'",
  ME2056: "o_c_customer_information-ны рresident_family_isforeign таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2057: "o_c_customer_information-ны рresident_family_isforeign таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME2058: "o_c_customer_information-ны рresident_family_registerno тааг байхгүй байна.'",
  ME2059: "o_c_customer_information-ны рresident_family_registerno таагийн утга буруу форматтай байна.'",
  ME2060: "o_c_customer_information-ны noofshareholders таагд оруулсан утга бүхэл тоо биш байна.'",
  ME2061: "o_bond таагийн аction нь байхгүй байна.'",
  ME2062: "o_bond таагийн аction-н утга нь жагсаалтанд байхгүй байна.'",
  ME2063: "o_bond-ны advamount тааг нь байхгүй байна.'",
  ME2064: "o_bond-ны advamount таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2065: "o_bond-ны advamount таагийн утгын бодит тоон утга биш байна.'",
  ME2066: "o_bond-ны advamount таагд оруулсан утгын формат буруу байна.'",
  ME2067: "o_bond-ны starteddate тааг нь байхгүй байна.'",
  ME2068: "o_bond-ны starteddate таагийн утга буруу форматтай байна.'",
  ME2069: "o_bond-ны еxpdate тааг нь байхгүй байна.'",
  ME2070: "o_bond-ны expdate таагийн утга буруу форматтай байна.'",
  ME2071: "o_bond-ны currencycode тааг нь байхгүй байна.'",
  ME2072: "o_bond-ны currencycode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2073: "o_bond-ны currencycode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2074: "o_bond-ны type тааг нь байхгүй байна.'",
  ME2075: "o_bond-ны type таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2076: "o_bond-ны type таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2077: "o_bond-ны bondmarket таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2078: "o_bond-ны numberofbonds тааг нь байхгүй байна.'",
  ME2079: "o_bond-ны numberofbond таагд оруулсан утга бүхэлт тоо биш байна.'",
  ME2080: "o_bond-ны bondunitprice тааг нь байхгүй байна.'",
  ME2081: "o_bond-ны bondunitprice таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2082: "o_bond-ны bondunitprice таагийн утга бодит тоон утга биш байна.'",
  ME2083: "o_bond-ны bondunitprice таагд оруулсан утгын формат буруу байна.'",
  ME2084: "o_bond-ны interestinperc тааг нь байхгүй байна.'",
  ME2085: "o_bond-ны interestinperc таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2086: "o_bond-ны interestinperc таагийн утга бодит тоон утга биш байна.'",
  ME2087: "o_bond-ны interestinperc таагд оруулсан утгын формат буруу байна.'",
  ME2100: "c_business таагийн Action нь байхгүй байна.'",
  ME2101: "c_business таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME2102: "c_business-ийн totalsale таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2103: "c_business-ийн totalsale таагийн утга бодит тоон утга биш байна.'",
  ME2104: "c_business-ийн totalsale таагд оруулсан утгын формат буруу байна.'",
  ME2105: "c_business-ийн totalcost таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2106: "c_business-ийн totalcost таагийн утга бодит тоон утга биш байна.'",
  ME2107: "c_business-ийн totalcost таагд оруулсан утгын формат буруу байна.'",
  ME2108: "c_business-ийн totalprofit таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2109: "c_business-ийн totalprofit таагийн утга бодит тоон утга биш байна.'",
  ME2110: "c_business-ийн totalprofit таагд оруулсан утгын формат буруу байна.'",
  ME2111: "c_business-ийн operatingexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2112: "c_business-ийн operatingexpense таагийн утга бодит тоон утга биш байна.'",
  ME2113: "c_business-ийн operatingexpense таагд оруулсан утгын формат буруу байна.'",
  ME2114: "c_business-ийн operatingincome таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2115: "c_business-ийн operatingincome таагийн утга бодит тоон утга биш байна.'",
  ME2116: "c_business-ийн operatingincome таагд оруулсан утгын формат буруу байна.'",
  ME2117: "c_business-ийн otherincome таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2118: "c_business-ийн otherincome таагийн утга бодит тоон утга биш байна.'",
  ME2119: "c_business-ийн otherincome таагд оруулсан утгын формат буруу байна.'",
  ME2120: "c_business-ийн otherexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2121: "c_business-ийн otherexpense таагийн утга бодит тоон утга биш байна.'",
  ME2122: "c_business-ийн otherexpense таагд оруулсан утгын формат буруу байна.'",
  ME2123: "c_business-ийн profitbeforetax таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2124: "c_business-ийн profitbeforetax таагийн утга бодит тоон утга биш байна.'",
  ME2125: "c_business-ийн profitbeforetax таагд оруулсан утгын формат буруу байна.'",
  ME2126: "c_business-ийн tax таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2127: "c_business-ийн tax таагийн утга бодит тоон утга биш байна.'",
  ME2128: "c_business-ийн tax таагд оруулсан утгын формат буруу байна.'",
  ME2129: "c_business-ийн netprofit таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2130: "c_business-ийн netprofit таагийн утга бодит тоон утга биш байна.'",
  ME2131: "c_business-ийн netprofit таагд оруулсан утгын формат буруу байна.'",
  ME2150: "c_capital таагийн Action нь байхгүй байна.'",
  ME2151: "c_capital таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME2152: "c_capital-ийн totalasset таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2153: "c_capital-ийн totalasset таагийн утга бодит тоон утга биш байна.'",
  ME2154: "c_capital-ийн totalasset таагд оруулсан утгын формат буруу байна.'",
  ME2155: "c_capital-ийн аssettype таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2156: "c_capital-ийн аssetcost таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2157: "c_capital-ийн аssetcost таагийн утга бодит тоон утга биш байна.'",
  ME2158: "c_capital-ийн assetсost таагд оруулсан утгын формат буруу байна.'",
  ME2159: "c_capital-ийн assetdepreciation таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2160: "c_capital-ийн assetdepreciation таагийн утга бодит тоон утга биш байна.'",
  ME2161: "c_capital-ийн assetdepreciation таагд оруулсан утгын формат буруу байна.'",
  ME2162: "c_capital-ийн assetownership таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2163: "Customers-ын datapackageno тааг нь байхгүй байна.'",
  ME2164: "Customers-ын datapackageno таагийн утга бүхэлт тоо биш байна.'",
  ME2180: "c_family таагийн Action нь байхгүй байна.'",
  ME2181: "c_family таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME2182: "c_family-ийн salary таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2183: "c_family-ийн salary таагийн утга бодит тоон утга биш байна.'",
  ME2184: "c_family-ийн salary таагд оруулсан утгын формат буруу байна.'",
  ME2185: "c_family-ийн otherincome таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2186: "c_family-ийн otherincome таагийн утга бодит тоон утга биш байна.'",
  ME2187: "c_family-ийн otherincome таагд оруулсан утгын формат буруу байна.'",
  ME2188: "c_family-ийн totalincome таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2189: "c_family-ийн totalincome таагийн утга бодит тоон утга биш байна.'",
  ME2190: "c_family-ийн totalincome таагд оруулсан утгын формат буруу байна.'",
  ME2191: "c_family-ийн foodexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2192: "c_family-ийн foodexpense таагийн утга бодит тоон утга биш байна.'",
  ME2193: "c_family-ийн foodexpense таагд оруулсан утгын формат буруу байна.'",
  ME2194: "c_family-ийн expensetolease таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2195: "c_family-ийн expensetolease таагийн утга бодит тоон утга биш байна.'",
  ME2196: "c_family-ийн expensetolease таагд оруулсан утгын формат буруу байна.'",
  ME2197: "c_family-ийн commexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2198: "c_family-ийн commexpense таагийн утга бодит тоон утга биш байна.'",
  ME2199: "c_family-ийн commexpense таагд оруулсан утгын формат буруу байна.'",
  ME2200: "c_family-ийн otherexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2201: "c_family-ийн otherexpense таагийн утга бодит тоон утга биш байна.'",
  ME2202: "c_family-ийн otherexpense таагд оруулсан утгын формат буруу байна.'",
  ME2203: "c_family-ийн totalexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2204: "c_family-ийн totalexpense таагийн утга бодит тоон утга биш байна.'",
  ME2205: "c_family-ийн totalexpense таагд оруулсан утгын формат буруу байна.'",
  ME2206: "c_family-ийн netincome таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2207: "c_family-ийн netincome таагийн утга бодит тоон утга биш байна.'",
  ME2208: "c_family-ийн netincome таагд оруулсан утгын формат буруу байна.'",
  ME2209: "c_family-ийн saving таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2210: "c_family-ийн saving таагийн утга бодит тоон утга биш байна.'",
  ME2211: "c_family-ийн saving таагд оруулсан утгын формат буруу байна.'",
  ME2212: "c_family-ийн totalsaving таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2213: "c_family-ийн totalsaving таагийн утга бодит тоон утга биш байна.'",
  ME2214: "c_family-ийн totalsaving таагд оруулсан утгын формат буруу байна.'",
  ME2215: "c_family-ийн savinghistory таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2216: "o_c_financial_information таагийн Action нь байхгүй байна.'",
  ME2217: "o_c_financial_information таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME2218: "o_c_financial_information таагийн date буруу форматтай байна.'",
  ME2219: "Graph таагийн Action нь байхгүй байна.'",
  ME2220: "Graph таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME2221: "Graph-ны datetopay тааг нь байхгүй байна.'",
  ME2222: "Graph-ны datetopay таагийн утга буруу форматтай байна.'",
  ME2223: "Graph-ны amounttopay тааг нь байхгүй байна.'",
  ME2224: "Graph-ны amounttopay таагд оруулсан утгын формат буруу байна.'",
  ME2250: "o_c_guarantee таагийн Action нь байхгүй байна.'",
  ME2251: "o_c_guarantee таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME2252: "o_c_guarantee таагийн advamount тааг нь байхгүй байна.'",
  ME2253: "o_c_guarantee таагийн advamount таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2254: "o_c_guarantee таагийн advamount таагийн утга бодит тоон утга биш байна.'",
  ME2255: "o_c_guarantee таагийн advamount таагд оруулсан утгын формат буруу байна.'",
  ME2256: "o_c_guarantee таагийн starteddate тааг нь байхгүй байна.'",
  ME2257: "o_c_guarantee таагийн starteddate буруу форматтай байна.'",
  ME2258: "o_c_guarantee таагийн expdate тааг нь байхгүй байна.'",
  ME2259: "o_c_guarantee таагийн expdate буруу форматтай байна.'",
  ME2260: "o_c_guarantee таагийн currencycode тааг нь байхгүй байна.'",
  ME2261: "o_c_guarantee таагийн currencycode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2262: "o_c_guarantee таагийн currencycode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2263: "o_c_guarantee таагийн type тааг нь байхгүй байна.'",
  ME2264: "o_c_guarantee таагийн type таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2265: "o_c_guarantee таагийн type таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2266: "o_c_guarantee таагийн interestinperc тааг нь байхгүй байна.'",
  ME2267: "o_c_guarantee таагийн interestinperc таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2268: "o_c_guarantee таагийн interestinperc таагийн утга бодит тоон утга биш байна.'",
  ME2269: "o_c_guarantee таагийн interestinperc таагд оруулсан утгын формат буруу байна.'",
  ME2270: "o_c_guarantee таагийн commissionperc тааг нь байхгүй байна.'",
  ME2271: "o_c_guarantee таагийн commissionperc таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2272: "o_c_guarantee таагийн commissionperc таагийн утга бодит тоон утга биш байна.'",
  ME2273: "o_c_guarantee таагийн commissionperc таагд оруулсан утгын формат буруу байна.'",
  ME2274: "o_c_guarantee таагийн fee тааг нь байхгүй байна.'",
  ME2275: "o_c_guarantee таагийн fee таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2276: "o_c_guarantee таагийн fee таагийн утга бодит тоон утга биш байна.'",
  ME2277: "o_c_guarantee таагийн fee таагд оруулсан утгын формат буруу байна.'",
  ME2278: "o_c_guarantee таагийн updatedexpdate буруу форматтай байна.'",
  ME2279: "o_c_guarantee таагийн extcount тааг нь байхгүй байна.'",
  ME2280: "o_c_guarantee таагийн extcount таагд оруулсан утга бүхэл тоо биш байна.'",
  ME2281: "o_c_guarantee таагийн extcount таагийн утгын урт заасан  хэмжээнээс хэтэрсэн байна.'",
  ME2300: "o_c_leasing таагийн Action нь байхгүй байна.'",
  ME2301: "o_c_leasing таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME2302: "o_c_leasing-ийн аdvamount тааг нь байхгүй байна.'",
  ME2303: "o_c_leasing-ийн аdvamount таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2304: "o_c_leasing-ийн аdvamount таагийн утга бодит тоон утга биш байна.'",
  ME2305: "o_c_leasing-ийн аdvamount таагд оруулсан утгын формат буруу байна.'",
  ME2306: "o_c_leasing-ийн starteddate тааг нь байхгүй байна.'",
  ME2307: "o_c_leasing-ийн starteddate буруу форматтай байна.'",
  ME2308: "o_c_leasing-ийн expdate тааг нь байхгүй байна.'",
  ME2309: "o_c_leasing-ийн expdate буруу форматтай байна.'",
  ME2310: "o_c_leasing-ийн currencycode тааг нь байхгүй байна.'",
  ME2311: "o_c_leasing-ийн currencycode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2312: "o_c_leasing-ийн currencycode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2313: "o_c_leasing-ийн interestinperc тааг нь байхгүй байна.'",
  ME2314: "o_c_leasing-ийн interestinperc таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2315: "o_c_leasing-ийн interestinperc таагийн утга бодит тоон утга биш байна.'",
  ME2316: "o_c_leasing-ийн interestinperc таагд оруулсан утгын формат буруу байна.'",
  ME2317: "o_c_leasing-ийн commissionperc тааг нь байхгүй байна.'",
  ME2318: "o_c_leasing-ийн commissionperc таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2319: "o_c_leasing-ийн commissionperc таагийн утга бодит тоон утга биш байна.'",
  ME2320: "o_c_leasing-ийн commissionperc таагд оруулсан утгын формат буруу байна.'",
  ME2321: "o_c_leasing-ийн fee тааг нь байхгүй байна.'",
  ME2322: "o_c_leasing-ийн fee таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2323: "o_c_leasing-ийн fee таагийн утга бодит тоон утга биш байна.'",
  ME2324: "o_c_leasing-ийн fee таагд оруулсан утгын формат буруу байна.'",
  ME2325: "o_c_leasing-ийн updatedexpdate буруу форматтай байна.'",
  ME2326: "o_c_leasing-ийн сlasscode тааг нь байхгүй байна.'",
  ME2327: "o_c_leasing-ийн сlasscode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2328: "o_c_leasing-ийн сlasscode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2350: "o_c_loan_information таагийн Action нь байхгүй байна.'",
  ME2351: "o_c_loan_information таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME2352: "o_c_loan_information-ийн provideLoanSize тааг нь байхгүй байна.'",
  ME2353: "o_c_loan_information-ийн provideLoanSize таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2354: "o_c_loan_information-ийн provideLoanSize таагийн утга бодит тоон утга биш байна.'",
  ME2355: "o_c_loan_information-ийн provideLoanSize таагд оруулсан утгын формат буруу байна.'",
  ME2356: "o_c_loan_information-ийн provenance тааг нь байхгүй байна.'",
  ME2357: "o_c_loan_information-ийн provenance таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2358: "o_c_loan_information-ийн provenance таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2359: "o_c_loan_information-ийн starteddate тааг нь байхгүй байна.'",
  ME2360: "o_c_loan_information-ийн starteddate буруу форматтай байна.'",
  ME2361: "o_c_loan_information-ийн expdate тааг нь байхгүй байна.'",
  ME2362: "o_c_loan_information-ийн expdate буруу форматтай байна.'",
  ME2363: "o_c_loan_information-ийн сurrencycode тааг нь байхгүй байна.'",
  ME2364: "o_c_loan_information-ийн сurrencycode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2365: "o_c_loan_information-ийн сurrencycode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2366: "o_c_loan_information-ийн interestinperc тааг нь байхгүй байна.'",
  ME2367: "o_c_loan_information-ийн interestinperc таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2368: "o_c_loan_information-ийн interestinperc таагийн утга бодит тоон утга биш байна.'",
  ME2369: "o_c_loan_information-ийн interestinperc таагд оруулсан утгын формат буруу байна.'",
  ME2370: "o_c_loan_information-ийн commissionperc тааг нь байхгүй байна.'",
  ME2371: "o_c_loan_information-ийн commissionperc таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2372: "o_c_loan_information-ийн commissionperc таагийн утга бодит тоон утга биш байна.'",
  ME2373: "o_c_loan_information-ийн commissionperc таагд оруулсан утгын формат буруу байна.'",
  ME2374: "o_c_loan_information-ийн fee тааг нь байхгүй байна.'",
  ME2375: "o_c_loan_information-ийн fee таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2376: "o_c_loan_information-ийн fee таагийн утга бодит тоон утга биш байна.'",
  ME2377: "o_c_loan_information-ийн fee таагд оруулсан утгын формат буруу байна.'",
  ME2378: "o_c_loan_information-ийн extdate буруу форматтай байна.'",
  ME2379: "o_c_loan_information-ийн updatedexpdate буруу форматтай байна.'",
  ME2380: "o_c_loan_information-ийн classcode тааг нь байхгүй байна.'",
  ME2381: "o_c_loan_information-ийн classcode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2382: "o_c_loan_information-ийн classcode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2400: "o_c_loanline таагийн Action нь байхгүй байна.'",
  ME2401: "o_c_loanline таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME2402: "o_c_loanline-ийн type тааг нь байхгүй байна.'",
  ME2403: "o_c_loanline-ийн type таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2404: "o_c_loanline-ийн type таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2405: "o_c_loanline-ийн сardno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2406: "o_c_loanline-ийн аdvamount тааг нь байхгүй байна.'",
  ME2407: "o_c_loanline-ийн аdvamount таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2408: "o_c_loanline-ийн аdvamount таагийн утга бодит тоон утга биш байна.'",
  ME2409: "o_c_loanline-ийн аdvamount таагд оруулсан утгын формат буруу байна.'",
  ME2410: "o_c_loanline-ийн starteddate тааг нь байхгүй байна.'",
  ME2411: "o_c_loanline-ийн starteddate буруу форматтай байна.'",
  ME2412: "o_c_loanline-ийн expdate тааг нь байхгүй байна.'",
  ME2413: "o_c_loanline-ийн expdate буруу форматтай байна.'",
  ME2414: "o_c_loanline-ийн сurrencycode тааг нь байхгүй байна.'",
  ME2415: "o_c_loanline-ийн сurrencycode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2416: "o_c_loanline-ийн сurrencycode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2417: "o_c_loanline-ийн loaninterest тааг нь байхгүй байна.'",
  ME2418: "o_c_loanline-ийн loaninterest таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2419: "o_c_loanline-ийн loaninterest таагийн утга бодит тоон утга биш байна.'",
  ME2420: "o_c_loanline-ийн loaninterest таагд оруулсан утгын формат буруу байна.'",
  ME2421: "o_c_loanline-ийн timestoloan тааг нь байхгүй байна.'",
  ME2422: "o_c_loanline-ийн timestoloan таагд оруулсан утга бүхэл тоо биш байна.'",
  ME2423: "o_c_loanline-ийн extdate буруу форматтай байна.'",
  ME2424: "o_c_loanline-ийн interestinperc тааг нь байхгүй байна.'",
  ME2425: "o_c_loanline-ийн interestinperc таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2426: "o_c_loanline-ийн interestinperc таагийн утга бодит тоон утга биш байна.'",
  ME2427: "o_c_loanline-ийн interestinperc таагд оруулсан утгын формат буруу байна.'",
  ME2428: "o_c_loanline-ийн commissionperc тааг нь байхгүй байна.'",
  ME2429: "o_c_loanline-ийн commissionperc таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2430: "o_c_loanline-ийн commissionperc таагийн утга бодит тоон утга биш байна.'",
  ME2431: "o_c_loanline-ийн commissionperc таагд оруулсан утгын формат буруу байна.'",
  ME2432: "o_c_loanline-ийн fee тааг нь байхгүй байна.'",
  ME2433: "o_c_loanline-ийн fee таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2434: "o_c_loanline-ийн fee таагийн утга бодит тоон утга биш байна.'",
  ME2435: "o_c_loanline-ийн fee таагд оруулсан утгын формат буруу байна.'",
  ME2450: "o_c_mortgage таагийн Action нь байхгүй байна.'",
  ME2451: "o_c_mortgage таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME2452: "o_c_mortgage-ийн mrtno тааг нь байхгүй байна.'",
  ME2453: "o_c_mortgage-ийн mrtno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2454: "o_c_mortgage-ийн mrtcode тааг нь байхгүй байна.'",
  ME2455: "o_c_mortgage-ийн mrtcode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2456: "o_c_mortgage-ийн mrtcode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2457: "o_c_mortgage-ийн mrtsubcode тааг нь байхгүй байна.'",
  ME2458: "o_c_mortgage-ийн mrtsubcode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2459: "o_c_mortgage-ийн mrtsubcode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2460: "o_c_mortgage-ийн mrtdescription тааг нь байхгүй байна.'",
  ME2461: "o_c_mortgage-ийн mrtdescription таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2462: "o_c_mortgage-ийн mrtregistereddate тааг нь байхгүй байна.'",
  ME2463: "o_c_mortgage-ийн mrtregistereddate буруу форматтай байна.'",
  ME2464: "o_c_mortgage-ийн mrtstateregisterno тааг нь байхгүй байна.'",
  ME2465: "o_c_mortgage-ийн mrtstateregisterno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2466: "o_c_mortgage-ийн mrtcertificateno тааг нь байхгүй байна.'",
  ME2467: "o_c_mortgage-ийн mrtcertificateno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2468: "o_c_mortgage-ийн mrtconfirmeddate тааг нь байхгүй байна.'",
  ME2469: "o_c_mortgage-ийн mrtconfirmeddate буруу форматтай байна.'",
  ME2470: "o_c_mortgage-ийн mrtorgname тааг нь байхгүй байна.'",
  ME2471: "o_c_mortgage-ийн mrtorgname таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2472: "o_c_mortgage-ийн mrtorgname таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2473: "o_c_mortgage-ийн mrtregistereddatefim тааг нь байхгүй байна.'",
  ME2474: "o_c_mortgage-ийн mrtregistereddatefim буруу форматтай байна.'",
  ME2475: "o_c_mortgage-ийн mrtregisterno тааг нь байхгүй байна.'",
  ME2476: "o_c_mortgage-ийн mrtregisterno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2477: "o_c_mortgage-ийн mrtcertificatenofim тааг нь байхгүй байна.'",
  ME2478: "o_c_mortgage-ийн mrtcertificatenofim таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2479: "o_c_mortgage-ийн dateofvaluation тааг нь байхгүй байна.'",
  ME2480: "o_c_mortgage-ийн dateofvaluation буруу форматтай байна.'",
  ME2481: "o_c_mortgage-ийн mrtvalue тааг нь байхгүй байна.'",
  ME2482: "o_c_mortgage-ийн mrtvalue таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2483: "o_c_mortgage-ийн mrtvalue таагийн утга бодит тоон утга биш байна.'",
  ME2484: "o_c_mortgage-ийн mrtvalue таагд оруулсан утгын формат буруу байна.'",
  ME2485: "o_c_mortgage-ийн mrtmaxlimit тааг нь байхгүй байна.'",
  ME2486: "o_c_mortgage-ийн mrtmaxlimit таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2487: "o_c_mortgage-ийн mrtmaxlimit таагийн утга бодит тоон утга биш байна.'",
  ME2488: "o_c_mortgage-ийн mrtmaxlimit таагд оруулсан утгын формат буруу байна.'",
  ME2489: "o_c_mortgage-ийн customer_firstname тааг нь байхгүй байна.'",
  ME2490: "o_c_mortgage-ийн customer_firstname таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2491: "o_c_mortgage-ийн customer_lastname таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2492: "o_c_mortgage-ийн customer_isforeign тааг нь байхгүй байна.'",
  ME2493: "o_c_mortgage-ийн customer_isforeign таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME2494: "o_c_mortgage-ийн customer_registerno тааг нь байхгүй байна.'",
  ME2495: "o_c_mortgage-ийн customer_registerno буруу форматтай байна.'",
  ME2496: "o_c_mortgage-ийн organization_orgname тааг нь байхгүй байна.'",
  ME2497: "o_c_mortgage-ийн organization_orgname таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2498: "o_c_mortgage-ийн organization_localregistered тааг нь байхгүй байна.'",
  ME2499: "o_c_mortgage-ийн organization_localregistered таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME2500: "o_c_mortgage-ийн organization_orgregisterno тааг нь байхгүй байна.'",
  ME2501: "o_c_mortgage-ийн organization_orgregisterno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2502: "o_c_mortgage-ийн organization_stateregisterno тааг нь байхгүй байна.'",
  ME2503: "o_c_mortgage-ийн organization_stateregisterno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2504: "o_c_mortgage-ийн mrt_zipcode тааг нь байхгүй байна.'",
  ME2505: "o_c_mortgage-ийн mrt_zipcode таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2506: "o_c_mortgage-ийн mrt_address тааг нь байхгүй байна.'",
  ME2507: "o_c_mortgage-ийн mrt_address таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME2508: "o_c_mortgage-ийн causetoshiftto тааг нь байхгүй байна.'",
  ME2509: "o_c_mortgage-ийн causetoshiftto таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME2510: "o_c_mortgage-ийн causetoshiftto таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME2511: "o_c_mortgage-ийн сourtorderdate буруу форматтай байна.'",
  ME2512: "o_c_mortgage-ийн сourtorderno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3000: "Loancharttype тааг нь байхгүй байна.'",
  ME3001: "Loancharttype таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3002: "Loancharttype таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3003: "Interestcharttype тааг нь байхгүй байна.'",
  ME3004: "Interestcharttype таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3005: "Interestcharttype таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3006: "c_staff_bankrelations таагийн Action нь байхгүй байна.'",
  ME3007: "c_staff_bankrelations таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME3008: "c_staff_bankrelations-ийн bankrelationtype тааг нь байхгүй байна.'",
  ME3009: "c_staff_bankrelations-ийн bankrelationtype таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3010: "c_staff_bankrelations-ийн bankrelationtype таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3011: "c_staff_bankrelations-ийн hiredate тааг нь байхгүй байна.'",
  ME3012: "c_staff_bankrelations-ийн hiredate буруу форматтай байна.'",
  ME3013: "c_staff_bankrelations-ийн firedate тааг нь байхгүй байна.'",
  ME3014: "c_staff_bankrelations-ийн firedate буруу форматтай байна.'",
  ME3020: "o_shareholderorg таагийн Action нь байхгүй байна.'",
  ME3021: "o_shareholderorg таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME3022: "o_shareholderorg-ийн orgname тааг нь байхгүй байна.'",
  ME3023: "o_shareholderorg-ийн orgname таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3024: "o_shareholderorg-ийн isforeign тааг нь байхгүй байна.'",
  ME3025: "o_shareholderorg-ийн isforeign таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME3026: "o_shareholderorg-ийн isforeign таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3027: "o_shareholderorg-ийн registerno тааг нь байхгүй байна.'",
  ME3028: "o_shareholderorg-ийн registerno буруу форматтай байна.'",
  ME3029: "o_shareholderorg-ийн registerno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3030: "o_shareholdercustomer таагийн Action нь байхгүй байна.'",
  ME3031: "o_shareholdercustomer таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME3032: "o_shareholdercustomer-ийн firstname тааг нь байхгүй байна.'",
  ME3033: "o_shareholdercustomer-ийн firstname таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3034: "o_shareholdercustomer-ийн lastname таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3035: "o_shareholdercustomer-ийн isforeign тааг нь байхгүй байна.'",
  ME3036: "o_shareholdercustomer-ийн isforeign таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME3037: "o_shareholdercustomer-ийн isforeign таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3038: "o_shareholdercustomer-ийн registerno тааг нь байхгүй байна.'",
  ME3039: "o_shareholdercustomer-ийн registerno буруу форматтай байна.'",
  ME3040: "o_c_sectorcodes таагийн sectorcode тааг нь байхгүй байна.'",
  ME3041: "o_c_sectorcodes таагийн sectorcode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3042: "o_c_sectorcodes таагийн Action нь байхгүй байна.'",
  ME3043: "o_c_sectorcodes таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME3044: "o_c_sectorcodes таагийн sectorcode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3050: "o_t_Report таагийн Action нь байхгүй байна.'",
  ME3051: "o_t_Report таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME3052: "o_t_Report-ийн t_circulatoryasset таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3053: "o_t_Report-ийн t_circulatoryasset таагийн утга бодит тоон утга биш байна.'",
  ME3054: "o_t_Report-ийн t_circulatoryasset таагд оруулсан утгын формат буруу байна.'",
  ME3055: "o_t_Report-ийн te_cash таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3056: "o_t_Report-ийн te_cash таагийн утга бодит тоон утга биш байна.'",
  ME3057: "o_t_Report-ийн te_cash таагд оруулсан утгын формат буруу байна.'",
  ME3058: "o_t_Report-ийн te_receivable таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3059: "o_t_Report-ийн te_receivable таагийн утга бодит тоон утга биш байна.'",
  ME3060: "o_t_Report-ийн te_receivable таагд оруулсан утгын формат буруу байна.'",
  ME3061: "o_t_Report-ийн te_material таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3062: "o_t_Report-ийн te_material таагийн утга бодит тоон утга биш байна.'",
  ME3063: "o_t_Report-ийн te_material таагд оруулсан утгын формат буруу байна.'",
  ME3064: "o_t_Report-ийн te_shortitmeinvest таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3065: "o_t_Report-ийн te_shortitmeinvest таагийн утга бодит тоон утга биш байна.'",
  ME3066: "o_t_Report-ийн te_shortitmeinvest таагд оруулсан утгын формат буруу байна.'",
  ME3067: "o_t_Report-ийн te_otherasset таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3068: "o_t_Report-ийн te_otherasset таагийн утга бодит тоон утга биш байна.'",
  ME3069: "o_t_Report-ийн te_otherasset таагд оруулсан утгын формат буруу байна.'",
  ME3070: "o_t_Report-ийн t_noncirculatoryasset таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3071: "o_t_Report-ийн t_noncirculatoryasset таагийн утга бодит тоон утга биш байна.'",
  ME3072: "o_t_Report-ийн t_noncirculatoryasset таагд оруулсан утгын формат буруу байна.'",
  ME3073: "o_t_Report-ийн tu_building таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3074: "o_t_Report-ийн tu_building таагийн утга бодит тоон утга биш байна.'",
  ME3075: "o_t_Report-ийн tu_building таагд оруулсан утгын формат буруу байна.'",
  ME3076: "o_t_Report-ийн tu_equipment таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3077: "o_t_Report-ийн tu_equipment таагийн утга бодит тоон утга биш байна.'",
  ME3078: "o_t_Report-ийн tu_equipment таагд оруулсан утгын формат буруу байна.'",
  ME3079: "o_t_Report-ийн tu_furniture таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3080: "o_t_Report-ийн tu_furniture таагийн утга бодит тоон утга биш байна.'",
  ME3081: "o_t_Report-ийн tu_furniture таагд оруулсан утгын формат буруу байна.'",
  ME3082: "o_t_Report-ийн tu_othertangible таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3083: "o_t_Report-ийн tu_othertangible таагийн утга бодит тоон утга биш байна.'",
  ME3084: "o_t_Report-ийн tu_othertangible таагд оруулсан утгын формат буруу байна.'",
  ME3085: "o_t_Report-ийн tu_accumdeppression таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3086: "o_t_Report-ийн tu_accumdeppression таагийн утга бодит тоон утга биш байна.'",
  ME3087: "o_t_Report-ийн tu_accumdeppression таагд оруулсан утгын формат буруу байна.'",
  ME3088: "o_t_Report-ийн t_totalasset таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3089: "o_t_Report-ийн t_totalasset таагийн утга бодит тоон утга биш байна.'",
  ME3090: "o_t_Report-ийн t_totalasset таагд оруулсан утгын формат буруу байна.'",
  ME3091: "o_t_Report-ийн t_shorttimeloan таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3092: "o_t_Report-ийн t_shorttimeloan таагийн утга бодит тоон утга биш байна.'",
  ME3093: "o_t_Report-ийн t_shorttimeloan таагд оруулсан утгын формат буруу байна.'",
  ME3094: "o_t_Report-ийн tb_loanonaccount таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3095: "o_t_Report-ийн tb_loanonaccount таагийн утга бодит тоон утга биш байна.'",
  ME3096: "o_t_Report-ийн tb_loanonaccount таагд оруулсан утгын формат буруу байна.'",
  ME3097: "o_t_Report-ийн tb_bankloan таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3098: "o_t_Report-ийн tb_bankloan таагийн утга бодит тоон утга биш байна.'",
  ME3099: "o_t_Report-ийн tb_bankloan таагд оруулсан утгын формат буруу байна.'",
  ME3100: "o_t_Report-ийн tb_othershorttime таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3101: "o_t_Report-ийн tb_othershorttime таагийн утга бодит тоон утга биш байна.'",
  ME3102: "o_t_Report-ийн tb_othershorttime таагд оруулсан утгын формат буруу байна.'",
  ME3103: "o_t_Report-ийн t_longtimeloan таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3104: "o_t_Report-ийн t_longtimeloan таагийн утга бодит тоон утга биш байна.'",
  ME3105: "o_t_Report-ийн t_longtimeloan таагд оруулсан утгын формат буруу байна.'",
  ME3106: "o_t_Report-ийн t_ownerproperty таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3107: "o_t_Report-ийн t_ownerproperty таагийн утга бодит тоон утга биш байна.'",
  ME3108: "o_t_Report-ийн t_ownerproperty таагд оруулсан утгын формат буруу байна.'",
  ME3109: "o_t_Report-ийн tz_companyfund таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3110: "o_t_Report-ийн tz_companyfund таагийн утга бодит тоон утга биш байна.'",
  ME3111: "o_t_Report-ийн tz_companyfund таагд оруулсан утгын формат буруу байна.'",
  ME3112: "o_t_Report-ийн tz_other таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3113: "o_t_Report-ийн tz_other таагийн утга бодит тоон утга биш байна.'",
  ME3114: "o_t_Report-ийн tz_other таагд оруулсан утгын формат буруу байна.'",
  ME3115: "o_t_Report-ийн tz_accumprofit таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3116: "o_t_Report-ийн tz_accumprofit таагийн утга бодит тоон утга биш байна.'",
  ME3117: "o_t_Report-ийн tz_accumprofit таагд оруулсан утгын формат буруу байна.'",
  ME3118: "o_t_Report-ийн t_debtownerproperty таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3119: "o_t_Report-ийн t_debtownerproperty таагийн утга бодит тоон утга биш байна.'",
  ME3120: "o_t_Report-ийн t_debtownerproperty таагд оруулсан утгын формат буруу байна.'",
  ME3150: "o_m_Report таагийн Action нь байхгүй байна.'",
  ME3151: "o_m_Report таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME3152: "o_m_Report-ийн m_operatingmoneyflow таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3153: "o_m_Report-ийн m_operatingmoneyflow таагийн утга бодит тоон утга биш байна.'",
  ME3154: "o_m_Report-ийн m_operatingmoneyflow таагд оруулсан утгын формат буруу байна.'",
  ME3155: "o_m_Report-ийн mu_profitbeforetaxinterest таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3156: "o_m_Report-ийн mu_profitbeforetaxinterest таагийн утга бодит тоон утга биш байна.'",
  ME3157: "o_m_Report-ийн mu_profitbeforetaxinterest таагд оруулсан утгын формат буруу байна.'",
  ME3158: "o_m_Report-ийн mu_deppressionexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3159: "o_m_Report-ийн mu_deppressionexpense таагийн утга бодит тоон утга биш байна.'",
  ME3160: "o_m_Report-ийн mu_deppressionexpense таагд оруулсан утгын формат буруу байна.'",
  ME3161: "o_m_Report-ийн mu_tax таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3162: "o_m_Report-ийн mu_tax таагийн утга бодит тоон утга биш байна.'",
  ME3163: "o_m_Report-ийн mu_tax таагд оруулсан утгын формат буруу байна.'",
  ME3164: "o_m_Report-ийн mu_materialprocurement таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3165: "o_m_Report-ийн mu_materialprocurement таагийн утга бодит тоон утга биш байна.'",
  ME3166: "o_m_Report-ийн mu_materialprocurement таагд оруулсан утгын формат буруу байна.'",
  ME3167: "o_m_Report-ийн m_financemoneyflow таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3168: "o_m_Report-ийн m_financemoneyflow таагийн утга бодит тоон утга биш байна.'",
  ME3169: "o_m_Report-ийн m_financemoneyflow таагд оруулсан утгын формат буруу байна.'",
  ME3170: "o_m_Report-ийн ms_receivablechange таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3171: "o_m_Report-ийн ms_receivablechange таагийн утга бодит тоон утга биш байна.'",
  ME3172: "o_m_Report-ийн ms_receivablechange таагд оруулсан утгын формат буруу байна.'",
  ME3173: "o_m_Report-ийн ms_shorttimeinvestchange таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3174: "o_m_Report-ийн ms_shorttimeinvestchange таагийн утга бодит тоон утга биш байна.'",
  ME3175: "o_m_Report-ийн ms_shorttimeinvestchange таагд оруулсан утгын формат буруу байна.'",
  ME3176: "o_m_Report-ийн ms_loanonaccountchange таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3177: "o_m_Report-ийн ms_loanonaccountchange таагийн утга бодит тоон утга биш байна.'",
  ME3178: "o_m_Report-ийн ms_loanonaccountchange таагд оруулсан утгын формат буруу байна.'",
  ME3179: "o_m_Report-ийн ms_bankloanchange таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3180: "o_m_Report-ийн ms_bankloanchange таагийн утга бодит тоон утга биш байна.'",
  ME3181: "o_m_Report-ийн ms_bankloanchange таагд оруулсан утгын формат буруу байна.'",
  ME3182: "o_m_Report-ийн ms_longtermsource таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3183: "o_m_Report-ийн ms_longtermsource таагийн утга бодит тоон утга биш байна.'",
  ME3184: "o_m_Report-ийн ms_longtermsource таагд оруулсан утгын формат буруу байна.'",
  ME3185: "o_m_Report-ийн ms_interestexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3186: "o_m_Report-ийн ms_interestexpense таагийн утга бодит тоон утга биш байна.'",
  ME3187: "o_m_Report-ийн ms_interestexpense таагд оруулсан утгын формат буруу байна.'",
  ME3188: "o_m_Report-ийн ms_ownerproperty таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3189: "o_m_Report-ийн ms_ownerproperty таагийн утга бодит тоон утга биш байна.'",
  ME3190: "o_m_Report-ийн ms_ownerproperty таагд оруулсан утгын формат буруу байна.'",
  ME3191: "o_m_Report-ийн ms_earningforshare таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3192: "o_m_Report-ийн ms_earningforshare таагийн утга бодит тоон утга биш байна.'",
  ME3193: "o_m_Report-ийн ms_earningforshare таагд оруулсан утгын формат буруу байна.'",
  ME3194: "o_m_Report-ийн mh_building таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3195: "o_m_Report-ийн mh_building таагийн утга бодит тоон утга биш байна.'",
  ME3196: "o_m_Report-ийн mh_building таагд оруулсан утгын формат буруу байна.'",
  ME3200: "o_m_Report-ийн mh_equipment таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3201: "o_m_Report-ийн mh_equipment таагийн утга бодит тоон утга биш байна.'",
  ME3202: "o_m_Report-ийн mh_equipment таагд оруулсан утгын формат буруу байна.'",
  ME3203: "o_m_Report-ийн mh_furniture таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3204: "o_m_Report-ийн mh_furniture таагийн утга бодит тоон утга биш байна.'",
  ME3205: "o_m_Report-ийн mh_furniture таагд оруулсан утгын формат буруу байна.'",
  ME3206: "o_m_Report-ийн mh_othertangible таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3207: "o_m_Report-ийн mh_othertangible таагийн утга бодит тоон утга биш байна.'",
  ME3208: "o_m_Report-ийн mh_othertangible таагд оруулсан утгын формат буруу байна.'",
  ME3209: "o_m_Report-ийн mh_otherintangible таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3210: "o_m_Report-ийн mh_otherintangible таагийн утга бодит тоон утга биш байна.'",
  ME3211: "o_m_Report-ийн mh_otherintangible таагд оруулсан утгын формат буруу байна.'",
  ME3212: "o_m_Report-ийн mh_accumdepression таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3213: "o_m_Report-ийн mh_accumdepression таагийн утга бодит тоон утга биш байна.'",
  ME3214: "o_m_Report-ийн mh_accumdepression таагд оруулсан утгын формат буруу байна.'",
  ME3215: "o_m_Report-ийн m_totalmoneyflow таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3216: "o_m_Report-ийн m_totalmoneyflow таагийн утга бодит тоон утга биш байна.'",
  ME3217: "o_m_Report-ийн m_totalmoneyflow таагд оруулсан утгын формат буруу байна.'",
  ME3218: "o_m_Report-ийн m_cashbalance таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3219: "o_m_Report-ийн m_cashbalance таагийн утга бодит тоон утга биш байна.'",
  ME3220: "o_m_Report-ийн m_cashbalance таагд оруулсан утгын формат буруу байна.'",
  ME3250: "o_Report таагийн Action нь байхгүй байна.'",
  ME3251: "o_Report таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME3252: "o_Report-ийн sale таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3253: "o_Report-ийн sale таагийн утга бодит тоон утга биш байна.'",
  ME3254: "o_Report-ийн sale таагд оруулсан утгын формат буруу байна.'",
  ME3255: "o_Report-ийн saleproductcost таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3256: "o_Report-ийн saleproductcost таагийн утга бодит тоон утга биш байна.'",
  ME3257: "o_Report-ийн saleproductcost таагд оруулсан утгын формат буруу байна.'",
  ME3258: "o_Report-ийн totalincome таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3259: "o_Report-ийн totalincome таагийн утга бодит тоон утга биш байна.'",
  ME3260: "o_Report-ийн totalincome таагд оруулсан утгын формат буруу байна.'",
  ME3261: "o_Report-ийн operatingexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3262: "o_Report-ийн operatingexpense таагийн утга бодит тоон утга биш байна.'",
  ME3263: "o_Report-ийн operatingexpense таагд оруулсан утгын формат буруу байна.'",
  ME3264: "o_Report-ийн ou_salary таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3265: "o_Report-ийн ou_salary таагийн утга бодит тоон утга биш байна.'",
  ME3266: "o_Report-ийн ou_salary таагд оруулсан утгын формат буруу байна.'",
  ME3267: "o_Report-ийн ou_leaseexploitexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3268: "o_Report-ийн ou_leaseexploitexpense таагийн утга бодит тоон утга биш байна.'",
  ME3269: "o_Report-ийн ou_leaseexploitexpense таагд оруулсан утгын формат буруу байна.'",
  ME3270: "o_Report-ийн ou_advertiseexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3271: "o_Report-ийн ou_advertiseexpense таагийн утга бодит тоон утга биш байна.'",
  ME3272: "o_Report-ийн ou_advertiseexpense таагд оруулсан утгын формат буруу байна.'",
  ME3273: "o_Report-ийн ou_insuranceexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3274: "o_Report-ийн ou_insuranceexpense таагийн утга бодит тоон утга биш байна.'",
  ME3275: "o_Report-ийн ou_insuranceexpense таагд оруулсан утгын формат буруу байна.'",
  ME3276: "o_Report-ийн ou_depreciationexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3277: "o_Report-ийн ou_depreciationexpense таагийн утга бодит тоон утга биш байна.'",
  ME3278: "o_Report-ийн ou_depreciationexpense таагд оруулсан утгын формат буруу байна.'",
  ME3279: "o_Report-ийн ou_otherexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3280: "o_Report-ийн ou_otherexpense таагийн утга бодит тоон утга биш байна.'",
  ME3281: "o_Report-ийн ou_otherexpense таагд оруулсан утгын формат буруу байна.'",
  ME3282: "o_Report-ийн minoroperincomeexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3283: "o_Report-ийн minoroperincomeexpense таагийн утга бодит тоон утга биш байна.'",
  ME3284: "o_Report-ийн minoroperincomeexpense таагд оруулсан утгын формат буруу байна.'",
  ME3285: "o_Report-ийн minoroperincome таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3286: "o_Report-ийн minoroperincome таагийн утга бодит тоон утга биш байна.'",
  ME3287: "o_Report-ийн minoroperincome таагд оруулсан утгын формат буруу байна.'",
  ME3288: "o_Report-ийн minoroperexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3289: "o_Report-ийн minoroperexpense таагийн утга бодит тоон утга биш байна.'",
  ME3290: "o_Report-ийн minoroperexpense таагд оруулсан утгын формат буруу байна.'",
  ME3291: "o_Report-ийн profitbeforetaxinterest таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3292: "o_Report-ийн profitbeforetaxinterest таагийн утга бодит тоон утга биш байна.'",
  ME3293: "o_Report-ийн profitbeforetaxinterest таагд оруулсан утгын формат буруу байна.'",
  ME3294: "o_Report-ийн oh_interestexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3295: "o_Report-ийн oh_interestexpense таагийн утга бодит тоон утга биш байна.'",
  ME3296: "o_Report-ийн oh_interestexpense таагд оруулсан утгын формат буруу байна.'",
  ME3297: "o_Report-ийн oh_tax таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3298: "o_Report-ийн oh_tax таагийн утга бодит тоон утга биш байна.'",
  ME3299: "o_Report-ийн oh_tax таагд оруулсан утгын формат буруу байна.'",
  ME3300: "o_Report-ийн netprofit таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3301: "o_Report-ийн netprofit таагийн утга бодит тоон утга биш байна.'",
  ME3302: "o_Report-ийн netprofit таагд оруулсан утгын формат буруу байна.'",
  ME3350: "c_staff_bankrelations-ийн bankrelationtype тааг нь байхгүй байна.'",
  ME3351: "c_staff_bankrelations-ийн bankrelationtype таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3352: "c_staff_bankrelations-ийн bankrelationtype таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3353: "c_staff_bankrelations-ийн hiredate тааг нь байхгүй байна.'",
  ME3354: "c_staff_bankrelations-ийн hiredate буруу форматтай байна.'",
  ME3355: "c_staff_bankrelations-ийн firedate тааг нь байхгүй байна.'",
  ME3356: "c_staff_bankrelations-ийн firedate буруу форматтай байна.'",
  ME3360: "o_c_relationorg таагийн Action нь байхгүй байна.'",
  ME3361: "o_c_relationorg таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME3362: "o_c_relationorg-ийн оrgname тааг нь байхгүй байна.'",
  ME3363: "o_c_relationorg-ийн оrgname таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3364: "o_c_relationorg-ийн isforeign тааг нь байхгүй байна.'",
  ME3365: "o_c_relationorg-ийн isforeign таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME3366: "o_c_relationorg-ийн registerno тааг нь байхгүй байна.'",
  ME3367: "o_c_relationorg-ийн registerno буруу форматтай байна.'",
  ME3368: "o_c_relationorg-ийн stateregisterno таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3369: "o_c_relationorg-ийн оrgrelation тааг нь байхгүй байна.'",
  ME3370: "o_c_relationorg-ийн оrgrelation таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3371: "o_c_relationorg-ийн оrgrelation таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3372: "o_c_relationorg-ийн isfinancialonus тааг нь байхгүй байна.'",
  ME3373: "o_c_relationorg-ийн isfinancialonus таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME3380: "o_c_relationcustomer таагийн Action нь байхгүй байна.'",
  ME3381: "o_c_relationcustomer таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME3382: "o_c_relationcustomer-ийн firstname тааг нь байхгүй байна.'",
  ME3383: "o_c_relationcustomer-ийн firstname таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3384: "o_c_relationcustomer-ийн lastname таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3385: "o_c_relationcustomer-ийн iIsforeign тааг нь байхгүй байна.'",
  ME3386: "o_c_relationcustomer-ийн iIsforeign таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME3387: "o_c_relationcustomer-ийн registerno тааг нь байхгүй байна.'",
  ME3388: "o_c_relationcustomer-ийн registerno буруу форматтай байна.'",
  ME3389: "o_c_relationcustomer-ийн сitizenrelation тааг нь байхгүй байна.'",
  ME3390: "o_c_relationcustomer-ийн сitizenrelation таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3391: "o_c_relationcustomer-ийн сitizenrelation таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3392: "o_c_relationcustomer-ийн isfinancialonus тааг нь байхгүй байна.'",
  ME3393: "o_c_relationcustomer-ийн isfinancialonus таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME3400: "o_c_receivable таагийн Action нь байхгүй байна.'",
  ME3401: "o_c_receivable таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME3402: "o_c_receivable-ийн advamount тааг нь байхгүй байна.'",
  ME3403: "o_c_receivable-ийн advamount таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3404: "o_c_receivable-ийн advamount таагийн утга бодит тоон утга биш байна.'",
  ME3405: "o_c_receivable-ийн advamount таагд оруулсан утгын формат буруу байна.'",
  ME3406: "o_c_receivable-ийн starteddate тааг нь байхгүй байна.'",
  ME3407: "o_c_receivable-ийн starteddate буруу форматтай байна.'",
  ME3408: "o_c_receivable-ийн expdate тааг нь байхгүй байна.'",
  ME3409: "o_c_receivable-ийн expdate буруу форматтай байна.'",
  ME3410: "o_c_receivable-ийн currencycode тааг нь байхгүй байна.'",
  ME3411: "o_c_receivable-ийн currencycode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3412: "o_c_receivable-ийн currencycode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3413: "o_c_receivable-ийн type тааг нь байхгүй байна.'",
  ME3414: "o_c_receivable-ийн type таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3415: "o_c_receivable-ийн type таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3416: "o_c_receivable-ийн classcode тааг нь байхгүй байна.'",
  ME3417: "o_c_receivable-ийн classcode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3418: "o_c_receivable-ийн classcode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3419: "o_c_receivable-ийн extdate буруу форматтай байна.'",
  ME3450: "o_c_onus таагийн Action нь байхгүй байна.'",
  ME3451: "o_c_onus таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME3452: "o_c_onus-ийн аdvamount тааг нь байхгүй байна.'",
  ME3453: "o_c_onus-ийн аdvamount таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3454: "o_c_onus-ийн аdvamount таагийн утга бодит тоон утга биш байна.'",
  ME3455: "o_c_onus-ийн аdvamount таагд оруулсан утгын формат буруу байна.'",
  ME3456: "o_c_onus-ийн rightopeneddate тааг нь байхгүй байна.'",
  ME3457: "o_c_onus-ийн rightopeneddate буруу форматтай байна.'",
  ME3458: "o_c_onus-ийн starteddate тааг нь байхгүй байна.'",
  ME3459: "o_c_onus-ийн starteddate буруу форматтай байна.'",
  ME3460: "o_c_onus-ийн paymentfinaldate тааг нь байхгүй байна.'",
  ME3461: "o_c_onus-ийн paymentfinaldate буруу форматтай байна.'",
  ME3462: "o_c_onus-ийн expdate тааг нь байхгүй байна.'",
  ME3463: "o_c_onus-ийн expdate буруу форматтай байна.'",
  ME3464: "o_c_onus-ийн interestinperc3 тааг нь байхгүй байна.'",
  ME3465: "o_c_onus-ийн interestinperc3 таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3466: "o_c_onus-ийн interestinperc3 таагийн утга бодит тоон утга биш байна.'",
  ME3467: "o_c_onus-ийн interestinperc3 таагд оруулсан утгын формат буруу байна.'",
  ME3468: "o_c_onus-ийн commissionperc тааг нь байхгүй байна.'",
  ME3469: "o_c_onus-ийн commissionperc таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3470: "o_c_onus-ийн commissionperc таагийн утга бодит тоон утга биш байна.'",
  ME3471: "o_c_onus-ийн commissionperc таагд оруулсан утгын формат буруу байна.'",
  ME3472: "o_c_onus-ийн fee тааг нь байхгүй байна.'",
  ME3473: "o_c_onus-ийн fee таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3474: "o_c_onus-ийн fee таагийн утга бодит тоон утга биш байна.'",
  ME3475: "o_c_onus-ийн fee таагд оруулсан утгын формат буруу байна.'",
  ME3476: "o_c_onus-ийн classcode тааг нь байхгүй байна.'",
  ME3477: "o_c_onus-ийн classcode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3478: "o_c_onus-ийн classcode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3500: "NegaInfo таагийн Action нь байхгүй байна.'",
  ME3501: "NegaInfo таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME3502: "NegaInfo-ийн Orgmeasure таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3503: "NegaInfo-ийн Measuredate буруу форматтай байна.'",
  ME3504: "NegaInfo-ийн Measuredescription таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3505: "NegaInfo-ийн Causetostartcase таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3506: "NegaInfo-ийн Causetostartcase таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3507: "NegaInfo-ийн Datetstartcase буруу форматтай байна.'",
  ME3508: "NegaInfo-ийн Registertopolice таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME3509: "NegaInfo-ийн Registertopolicedate буруу форматтай байна.'",
  ME3510: "NegaInfo-ийн Timesinpolice таагийн утгын урт 2-оос хэтэрсэн байна.'",
  ME3511: "NegaInfo-ийн Registertoprocuror таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME3512: "NegaInfo-ийн Registertoprocurordate буруу форматтай байна.'",
  ME3513: "NegaInfo-ийн Timesinprocuror таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3514: "NegaInfo-ийн Registertocourt таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME3515: "NegaInfo-ийн Registertocourtdate буруу форматтай байна.'",
  ME3516: "NegaInfo-ийн Timesincourt таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3517: "NegaInfo-ийн Shiftocourt2 таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME3518: "NegaInfo-ийн Shifttocourt2date буруу форматтай байна.'",
  ME3519: "NegaInfo-ийн Timesincourt2 таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3520: "NegaInfo-ийн Shiftocourtdecision таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3521: "NegaInfo таагийн Shifttocourtdecisiondate буруу форматтай байна.'",
  ME3522: "NegaInfo-ийн Ignoredcrime таагд оруулсан утга 0 эсвэл 1 биш байна.'",
  ME3523: "NegaInfo-ийн Ignoreddate буруу форматтай байна.'",
  ME3524: "NegaInfo-ийн Courtorderno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3601: "o_shareholderorg-ийн stateregisterno таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME3602: "o_shareholdercustomer-ийн registerno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3603: "o_c_relationorg-ийн isforeign таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3604: "o_c_relationorg-ийн registerno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3605: "o_c_relationorg-ийн isfinancialonus таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3606: "o_c_relationcustomer-ийн iIsforeign таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3607: "o_c_relationcustomer-ийн registerno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3608: "o_c_relationcustomer-ийн isfinancialonus таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3609: "o_c_customer_information-ны isorganization таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3610: "o_c_customer_information-ны isforeign таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3611: "o_c_customer_information-ны рresident_family_registerno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3612: "o_c_customer_information-ны noofshareholders таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3613: "o_bond-ны numberofbond таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3614: "o_c_customer_information-ны registernо таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3615: "o_c_customer_information-ны stateregister_passportno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3616: "o_c_loanline-ийн timestoloan таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3617: "o_c_mortgage-ийн customer_isforeign таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3618: "o_c_mortgage-ийн customer_registerno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3619: "o_c_mortgage-ийн organization_localregistered таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3620: "NegaInfo-ийн Registertocourt таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3621: "NegaInfo-ийн Shiftocourt2 таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3622: "NegaInfo-ийн Ignoredcrime таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME3623: "MortgageNo-ийн MortgageNo таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3624: "Customer таг алдаатай байна.'",
  ME3625: "Customers таг алдаатай байна.'",
  ME3626: "Бүртгэлгүй хэрэглэгчээр нэвтрэх оролдлого бүртгэгдлээ.'",
  ME3627: "Хэрэглэгчийн нууц үг буруу байна.'",
  ME3628: "Хэрэглэгчийн IP хаяг буруу байна.'",
  ME3629: "Зээлдэгчийн bankCode буруу байна.'",
  ME3630: "Зээлдэгчийн branchcode буруу байна.'",
  ME3631: "- зээлдэгчийн мэдээллийг амжилттай орууллаа.'",
  ME3632: "- зээлдэгчийн мэдээлэлд дараах алдаа байна.'",
  ME3633: "- зээлдэгчийн мэдээллийг оруулах явцад алдаа гарсан тул мэдээлэл дутуу орсон. Монголбанкны МТГ-д хандана уу.'",
  ME3634: "хэрэглэгчийн orgcode хоосон байна.'",
  ME3635: "хэрэглэгчийн orgbranchcode хоосон байна.'",
  ME3636: "- зээлдэгчийн мэдээлэл хоосон байна.'",
  ME3637: "o_c_customer_information-ны isorganization таагийн байхгүй учир цааш шалгахгүй.'",
  ME3638: "NegaInfo таагийн Registertopolicedate таг байхгүй байна.'",
  ME3639: "o_c_customer_information-ны registerno таагийн утгын урт буруу байна.'",
  ME3640: "Хуулийн статус талбарын утга нь жагсаалтанд байхгүй байна.'",
  ME3641: "customercode тагийн регистр байхгүй байна.'",
  ME3642: "customercode-ийн регистр нь регистр тагийн утгатай тэнцэхгүй байна.'",
  ME3643: "o_c_bankCode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3644: "o_c_branchcode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME3645: "o_c_loan_balance тааг байхгүй байна.'",
  ME3646: "o_c_loan_balance тагийн утга заасан хэмжээнээс хэтэрсэн байна.'",
  ME3647: "o_c_loan_balance тагийн утга бодит тоон утга биш байна.'",
  ME3648: "o_c_loan_balance тагийн формат буруу байна.'",
  ME3649: "o_c_leasing_balance тааг байхгүй байна.'",
  ME3650: "o_c_leasing_balance тагийн утга заасан хэмжээнээс хэтэрсэн байна.'",
  ME3651: "o_c_leasing_balance тагийн утга бодит тоон утга биш байна.'",
  ME3652: "o_c_leasing_balance тагийн формат буруу байна.'",
  ME3653: "o_c_loanline_balance тааг байхгүй байна.'",
  ME3654: "o_c_loanline_balance тагийн утга заасан хэмжээнээс хэтэрсэн байна.'",
  ME3655: "o_c_loanline_balance тагийн утга бодит тоон утга биш байна.'",
  ME3656: "o_c_loanline_balance тагийн формат буруу байна.'",
  ME3657: "o_c_guarantee_balance эсвэл o_c_accredit_balance тааг байхгүй байна.'",
  ME3658: "o_c_guarantee_balance эсвэл o_c_accredit_balance тагийн утга заасан хэмжээнээс хэтэрсэн байна.'",
  ME3659: "o_c_guarantee_balance эсвэл o_c_accredit_balance тагийн утга бодит тоон утга биш байна.'",
  ME3660: "o_c_guarantee_balance эсвэл o_c_accredit_balance тагийн формат буруу байна.'",
  ME3661: "o_c_receivable_balance тааг байхгүй байна.'",
  ME3662: "o_c_receivable_balance тагийн утга заасан хэмжээнээс хэтэрсэн байна.'",
  ME3663: "o_c_receivable_balance тагийн утга бодит тоон утга биш байна.'",
  ME3664: "o_c_receivable_balance тагийн формат буруу байна.'",
  ME3665: "o_c_onus_balance тааг байхгүй байна.'",
  ME3666: "o_c_onus_balance тагийн утга заасан хэмжээнээс хэтэрсэн байна.'",
  ME3667: "o_c_onus_balance тагийн утга бодит тоон утга биш байна.'",
  ME3668: "o_c_onus_balance тагийн формат буруу байна.'",
  ME3669: "o_bond_balance тааг байхгүй байна.'",
  ME3670: "o_bond_balance тагийн утга заасан хэмжээнээс хэтэрсэн байна.'",
  ME3671: "o_bond_balance тагийн утга бодит тоон утга биш байна.'",
  ME3672: "o_bond_balance тагийн формат буруу байна.'",
  ME3673: "o_c_loandetail таг байхгүй байна.'",
  ME3674: "o_c_loaninterestdetail таг байхгүй байна'",
  ME3675: "o_c_leasingdetail таг байхгүй байна.'",
  ME3676: "o_c_leasinginterestdetail таг байхгүй байна.'",
  ME3677: "o_c_receivabledetail таг байхгүй байна.'",
  ME3678: "o_c_receivableinterestdetail таг байхгүй байна.'",
  ME3679: "o_c_onusdetail таг байхгүй байна.'",
  ME3680: "o_c_onusinterestdetail таг байхгүй байна.'",
  ME3681: "o_c_registeredtoauthority o_c_authorityofimmovable таагуудын аль нэг нь заавал байх хэрэгтэй.'",
  ME3682: "o_c_loandetail_datetopay тагийн утга давхцаж байна.'",
  ME3683: "o_c_loaninterestdetail_datetopay тагийн утга давхцаж байна.'",
  ME3684: "o_c_loanperformance_datetopay тагийн утга давхцаж байна.'",
  ME3685: "o_c_loaninterestperformance_datetopay тагийн утга давхцаж байна.'",
  ME3686: "o_c_leasingdetail_datetopay тагийн утга давхцаж байна.'",
  ME3687: "o_c_leasinginterestdetail_datetopay тагийн утга давхцаж байна.'",
  ME3688: "o_c_leasingperformance_datetopay тагийн утга давхцаж байна.'",
  ME3689: "o_c_leasinginterestperformance_datetopay тагийн утга давхцаж байна.'",
  ME3690: "o_c_receivabledetail_datetopay тагийн утга давхцаж байна.'",
  ME3691: "o_c_receivableinterestdetail_datetopay тагийн утга давхцаж байна.'",
  ME3692: "o_c_receivableperformance_datetopay тагийн утга давхцаж байна.'",
  ME3693: "o_c_receivableinterestperformance_datetopay тагийн утга давхцаж байна.'",
  ME3694: "o_c_onusdetail_datetopay тагийн утга давхцаж байна.'",
  ME3695: "o_c_onusinterestdetail_datetopay тагийн утга давхцаж байна.'",
  ME3696: "o_c_onusperformance_datetopay тагийн утга давхцаж байна.'",
  ME3697: "o_c_onusinterestperformance_datetopay тагийн утга давхцаж байна.'",
  ME4000: "o_report-ийн ou_fuelcommexpense таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME4001: "o_report-ийн ou_fuelcommexpense таагийн утга бодит тоон утга биш байна.'",
  ME4002: "o_report-ийн ou_fuelcommexpense таагд оруулсан утгын формат буруу байна.'",
  ME4003: "o_m_Report-ийн o_m_investmoneyflow таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME4004: "o_m_Report-ийн o_m_investmoneyflow таагийн утга бодит тоон утга биш байна.'",
  ME4005: "o_m_Report-ийн o_m_investmoneyflow таагд оруулсан утгын формат буруу байна.'",
  ME4006: "o_c_loan_sectorcode тааг нь байхгүй байна.'",
  ME4007: "o_c_loan_information-ийн o_c_loantransactions-ийн o_c_loan_loancharttype тааг нь байхгүй байна.'",
  ME4008: "o_c_loan_information-ийн o_c_loantransactions-ийн o_c_loan_loancharttype таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME4009: "o_c_loan_information-ийн o_c_loantransactions-ийн o_c_loan_loancharttype таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME4010: "o_c_loan_information таагийн o_c_loantransactions-ийн o_c_loandetails-ийн o_c_loandetail таагийн Action нь байхгүй байна.'",
  ME4011: "o_c_loan_information таагийн o_c_loantransactions-ийн o_c_loandetails-ийн o_c_loandetail таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME4012: "o_c_leasing_sectorcode тааг нь байхгүй байна.'",
  ME4013: "o_c_leasing-ийн o_c_leasingtransactions-ийн o_c_leasing_loancharttype тааг нь байхгүй байна.'",
  ME4014: "o_c_leasing-ийн o_c_leasingtransactions-ийн o_c_leasing_loancharttype таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME4015: "o_c_leasing-ийн o_c_leasingtransactions-ийн o_c_leasing_loancharttype таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME4016: "o_c_leasing-ийн o_c_leasingtransactions-ийн o_c_leasingdetails-ийн o_c_leasingdetail таагийн Action нь байхгүй байна.'",
  ME4017: "o_c_leasing-ийн o_c_leasingtransactions-ийн o_c_leasingdetails-ийн o_c_leasingdetail таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME4018: "o_c_loanline_sectorcode тааг нь байхгүй байна.'",
  ME4019: "o_c_loanline-ийн timestoloan таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME4020: "o_c_guarantee_sectorcode тааг нь байхгүй байна.'",
  ME4021: "o_c_accredit_sectorcode тааг нь байхгүй байна.'",
  ME4022: "o_c_mortgage-ийн o_c_is_real_estate тааг нь байхгүй байна.'",
  ME4023: "o_c_mortgage-ийн o_c_is_real_estate тааг-ийн утга нь 0 эсвэл 1 байна.'",
  ME4024: "o_c_mortgage-ийн o_c_customer o_c_organization таагуудын аль нэг нь заавал байх хэрэгтэй.'",
  ME4025: "o_c_mortgage-ийн customer_registerno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME4026: "o_c_loanline-ийн cardno таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME4027: "customercode-ийн сүүлийн 10 орон нь registerno-гоос ялгаатай байна.'",
  ME4028: "Хуулийн статусийг Монгол Улсын иргэн гэж ирүүлсэн боловч регистерийн дугаарын формат буруу байна.'",
  ME4029: "Хуулийн статусийг Монгол Улсын иргэн биш гэж ирүүлсэн боловч регистерийн дугаарыг Монгол Улсын иргэний регистерийн дугаарын форматын дагуу явуулсан байна.'",
  ME4030: "Зээлдэгчийн мэдээллийг өгөгдлийн сан уруу оруулахад алдаа гарлаа.'",
  ME4031: "Зээлдэгчийн мэдээлэлтэй ажиллахад алдаа гарлаа.'",
  ME4032: "Зээлдэгчийн дэлгэрэнгүй мэдээллийг өгөгдлийн сан уруу оруулахад алдаа гарлаа.'",
  ME4033: "Зээлдэгчийн дэлгэрэнгүй мэдээлэлтэй ажиллахад алдаа гарлаа.'",
  ME4034: "Зээлийн мэдээллийг өгөгдлийн сан уруу оруулахад алдаа гарлаа.'",
  ME4035: "Зээлийн мэдээлэлтэй ажиллахад алдаа гарлаа.'",
  ME4036: "Зээлийн балансийн мэдээллийг өгөгдлийн сан уруу оруулахад алдаа гарлаа.'",
  ME4037: "Зээлийн балансийн мэдээлэлтэй ажиллахад алдаа гарлаа.'",
  ME4038: "Зээлийн сөрөг мэдээллийг өгөгдлийн сан уруу оруулахад алдаа гарлаа.'",
  ME4039: "Зээлийн сөрөг мэдээлэлтэй ажиллахад алдаа гарлаа.'",
  ME4040: "Зээлийн графикийн дагуу төлөгдөх мэдээллийг өгөгдлийн сан уруу оруулахад алдаа гарлаа.'",
  ME4041: "Зээлийн графикийн дагуу төлөгдөх мэдээлэлтэй ажиллахад алдаа гарлаа.'",
  ME4042: "Зээлийн графикийн мэдээллийг өгөгдлийн сан уруу оруулахад алдаа гарлаа.'",
  ME4043: "Зээлийн графикийн мэдээлэлтэй ажиллахад алдаа гарлаа.'",
  ME4044: "Зээлийн графикийн дагуу төлсөн мэдээллийг өгөгдлийн сан уруу оруулахад алдаа гарлаа.'",
  ME4045: "Зээлийн графикийн дагуу төлсөн мэдээлэлтэй ажиллахад алдаа гарлаа.'",
  ME4046: "Зээлийн хүү графикийн дагуу төлөгдөх мэдээллийг өгөгдлийн сан уруу оруулахад алдаа гарлаа.'",
  ME4047: "Зээлийн хүү графикийн дагуу төлөгдөх мэдээлэлтэй ажиллахад алдаа гарлаа.'",
  ME4048: "Зээлийн хүү графикийн дагуу төлсөн мэдээллийг өгөгдлийн сан уруу оруулахад алдаа гарлаа.'",
  ME4049: "Зээлийн хүү графикийн дагуу төлсөн мэдээлэлтэй ажиллахад алдаа гарлаа.'",
  ME4050: "Зээлдэгчийн мэдээллийг өгөгдлийн сан уруу засч оруулахад алдаа гарлаа.'",
  ME4051: "Зээлдэгчийн мэдээллийг засахад алдаа гарлаа.'",
  ME4052: "Зээлийн мэдээллийг өгөгдлийн сан уруу засч оруулахад алдаа гарлаа.'",
  ME4053: "Зээлийн мэдээллийг засахад алдаа гарлаа.'",
  ME4054: "o_c_mortgage-ийн mrtno таагийн утга давхардаж байна.'",
  ME4055: "o_c_relationorg-ийн o_c_relationorg_relno таагийн утга эсвэл o_c_relationcustomer-ийн o_c_relationcustomer_relno таагийн утга давхардаж байна.'",
  ME4056: "o_c_relationorg-ийн o_c_relationorg_relno таагийн утга хоосон байна.'",
  ME4057: "o_c_relationcustomer-ийн o_c_relationcustomer_relno таагийн утга хоосон байна.'",
  ME4058: "Хамтран зээлдэгчийн мэдээллийг өгөгдлийн сан уруу оруулахад алдаа гарлаа.'",
  ME4059: "Хамтран зээлдэгчийн мэдээлэлтэй ажиллахад алдаа гарлаа.'",
  ME5000: "customer таагийн Action нь байхгүй байна.'",
  ME5001: "customer таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME5002: "o_c_customer_information тааг байхгүй байна.'",
  ME5003: "o_c_relationorg-ийн registerno таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME6000: "Хэрэглэгчийн нэр эсвэл нууц үг буруу байна.'",
  ME6001: "Хэрэглэгч XML файл нийлүүлэх эрхгүй байна.'",
  ME6002: "Нийлүүлсэн XML файл бүтцийн алдаатай байна.'",
  ME6003: "Хэрэглэгчийн байгууллагын код нь зээлдэгчийн o_c_bankCode-тэй зөрлөө.'",
  ME6004: "Зээлийн мэдээлэл хоосон байна.'",
  ME6005: "Зээлдэгч шинээр оруулж байхад зээлийн мэдээллийг засах үйлдэл хийх боломжгүй.'",
  ME6006: "Нийлүүлсэн XML файлын хэмжээ заасан хэмжээнээс их эсвэл бага байна.'",
  ME6007: "XML файл хоосон эсвэл XML файл хавсаргаагүй байна.'",
  ME6008: "XML файл хадгалахад алдаа гарлаа.'",
  ME6009: "customer таг байхгүй байна.'",
  ME6010: "Нийт зээлийн мэдээлэл устгах оролдлого гарлаа.'",
  ME6011: "Зээлийн мэдээлэл устгах оролдлого гарлаа.'",
  ME6012: "customer таагийн action add эсвэл insert байвал зээлийн мэдээллийн action update байж болохгүй.'",
  ME6013: "Зээл давхардсан байна.'",
  ME6014: "Давхардсан мэдээлэл байна.'",
  ME6015: "customer таагийн action update үед update хийх зээлдэгчийн мэдээлэл олдсонгүй.'",
  ME6016: "update хийх гэж байгаа зээл бүртгэгдээгүй байна.'",
  ME6017: "add хийх гэсэн барьцаа хөрөнгө уг зээлэнд өмнө нь бүртгэгдсэн байна.'",
  ME6019: "Хэрэглэгч идэвхигүй байна.'",
  ME6020: "customer таагийн action add үед o_c_customer_information таагийн action update байж болохгүй.'",
  ME6021: "Зээлдэгчийн мэдээлэл устгах оролдлогыг бүртгэлээ.'",
  ME6022: "customer таагийн action update үед o_c_customer_information таагийн action add байж болохгүй.'",
  ME6023: "update буюу шинэчлэх гэсэн барьцаа хөрөнгө тухайн зээлэнд бүртгэгдээгүй байна.'",
  ME6024: "delete буюу устгах гэсэн барьцаа хөрөнгө тухайн зээлэнд бүртгэгдээгүй байна.'",
  ME6025: "Нэмэх гэсэн хамтран зээлдэгч тухайн зээлэнд өмнө нь бүртгэгдсэн байна.'",
  ME6026: "Зээлдэгч нэмэхэд PK алдаа гарлаа.'",
  ME6027: "Зээлдэгчийн дэлгэрэнгүй мэдээлэл нэмэхэд PK алдаа гарлаа.'",
  ME7000: "o_c_accredit таагийн Action нь байхгүй байна.'",
  ME7001: "o_c_accredit таагийн Action-н утга нь жагсаалтанд байхгүй байна.'",
  ME7002: "o_c_accredit таагийн advamount тааг нь байхгүй байна.'",
  ME7003: "o_c_accredit таагийн advamount таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME7004: "o_c_accredit таагийн advamount таагийн утга бодит тоон утга биш байна.'",
  ME7005: "o_c_accredit таагийн advamount таагд оруулсан утгын формат буруу байна.'",
  ME7006: "o_c_accredit таагийн starteddate тааг нь байхгүй байна.'",
  ME7007: "o_c_accredit таагийн starteddate буруу форматтай байна.'",
  ME7008: "o_c_accredit таагийн expdate тааг нь байхгүй байна.'",
  ME7009: "o_c_accredit таагийн expdate буруу форматтай байна.'",
  ME7010: "o_c_accredit таагийн currencycode тааг нь байхгүй байна.'",
  ME7011: "o_c_accredit таагийн currencycode таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME7012: "o_c_accredit таагийн currencycode таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME7013: "o_c_accredit таагийн type тааг нь байхгүй байна.'",
  ME7014: "o_c_accredit таагийн type таагийн утгын урт заасан утгатай тэнцүү биш байна.'",
  ME7015: "o_c_accredit таагийн type таагийн утга нь жагсаалтанд байхгүй байна.'",
  ME7016: "o_c_accredit таагийн interestinperc тааг нь байхгүй байна.'",
  ME7017: "o_c_accredit таагийн interestinperc таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME7018: "o_c_accredit таагийн interestinperc таагийн утга бодит тоон утга биш байна.'",
  ME7019: "o_c_accredit таагийн interestinperc таагд оруулсан утгын формат буруу байна.'",
  ME7020: "o_c_accredit таагийн commissionperc тааг нь байхгүй байна.'",
  ME7021: "o_c_accredit таагийн commissionperc таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME7022: "o_c_accredit таагийн commissionperc таагийн утга бодит тоон утга биш байна.'",
  ME7023: "o_c_accredit таагийн commissionperc таагд оруулсан утгын формат буруу байна.'",
  ME7024: "o_c_accredit таагийн fee тааг нь байхгүй байна.'",
  ME7025: "o_c_accredit таагийн fee таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME7026: "o_c_accredit таагийн fee таагийн утга бодит тоон утга биш байна.'",
  ME7027: "o_c_accredit таагийн fee таагд оруулсан утгын формат буруу байна.'",
  ME7028: "o_c_accredit таагийн updatedexpdate буруу форматтай байна.'",
  ME7029: "o_c_accredit таагийн extcount тааг нь байхгүй байна.'",
  ME7030: "o_c_accredit таагийн extcount таагд оруулсан утга бүхэл тоо биш байна.'",
  ME7031: "o_c_accredit таагийн extcount таагийн утгын урт заасан хэмжээнээс хэтэрсэн байна.'",
  ME7032: "Илгээж буй зээлдэгчийн мэдээлэл нь Улсын бүртгэлийн сангаас зөрүүтэй байна.'",
  ME7033: "Илгээж буй зээлдэгчийн мэдээлэл нь Улсын бүртгэл сангаас олдсонгүй.'",
  ME7034: "Улсын бүртгэлийн сангаас регистрийн дугаараар мэдээлэл шалгах үед алдаа гарлаа.'",
  E10000: "Улсын бүртгэлээс мэдээлэл шалгахад алдаа гарлаа.'",
  E31101: "Зээлийн үлдэгдэл шинэчлэхэд өгөгдлийн сангийн алдаа гарлаа.'",
  E31102: "Зээлийн үлдэгдэл шинэчлэхэд алдаа гарлаа.'",
  E32001: "Зээл хаагдсан учраас шинэчлэх боломжгүй.'",
  E40200: "Холбогдох иргэн шинэчлэхэд PK алдаа гарлаа.'",
  E40201: "Холбогдох иргэн шинэчлэхэд өгөгдлийн сангийн алдаа гарлаа.'",
  E40202: "Холбогдох иргэн шинэчлэхэд алдаа гарлаа.'",
  W50101: "Барьцаа хөрөнгийн мэдээлэл нэмэхэд PK алдаа гарлаа.'",
  W50102: "Барьцаа хөрөнгийн мэдээлэл нэмэхэд өгөгдлийн сангийн алдаа гарлаа.'",
  W50103: "Барьцаа хөрөнгийн мэдээлэл нэмэхэд алдаа гарлаа.'",
  TE1000: "Лавлагаанд тусгагдахгүй төлөлт хийгдэж дууссан үүргийн мэдээлэл байна'"
};