import ERRORS from "./ERRORS";
import NOS_TYPES from "./NOS_TYPES";
import CLIENT_STATUS from "./CLIENT_STATUS";
import VALUE_CODES from "./VALUE_CODES";
import APPENDIX_A from "./APPENDIX_A";
import APPENDIX_C from "./APPENDIX_C";
import APPENDIX_D from "./APPENDIX_D";
import APPENDIX_EO from "./APPENDIX_EO";
import APPENDIX_E from "./APPENDIX_E";
import APPENDIX_ERH_ORG from "./APPENDIX_ERH_ORG";
import APPENDIX_G from "./APPENDIX_G";
import APPENDIX_J from "./APPENDIX_J";
import APPENDIX_K from "./APPENDIX_K";
import APPENDIX_L from "./APPENDIX_L";
import APPENDIX_M from "./APPENDIX_M";
import APPENDIX_MORTGAGE from "./APPENDIX_MORTGAGE";
import APPENDIX_N from "./APPENDIX_N";
import APPENDIX_O_LEGAL_STATUS from "./APPENDIX_O_LEGAL_STATUS";
import APPENDIX_O from "./APPENDIX_O";
import APPENDIX_P_FITCH from "./APPENDIX_P_FITCH";
import APPENDIX_PHI from "./APPENDIX_PHI";
import APPENDIX_T from "./APPENDIX_T";
import APPENDIX_I from "./APPENDIX_I";
import APPENDIX_Y from "./APPENDIX_Y";
import APPENDIX_X from "./APPENDIX_X";
import APPENDIX_Z from "./APPENDIX_Z";
import APPENDIX_R from "./APPENDIX_R";
import APPENDIX_PAYMENT_TYPE from "./APPENDIX_PAYMENT_TYPE";
import APPENDIX_HAGAS_I from "./APPENDIX_HAGAS_I";
import ERROR_DETAILS from "./ERROR_DETAILS";
import ERROR_CODES from "./ERROR_CODES";
import FORMATTABLE_VARIABLES from "./FORMATTABLE_VARIABLES";
let APPENDIX = {
  APPENDIX_HAGAS_I, APPENDIX_PAYMENT_TYPE, APPENDIX_R, APPENDIX_Z, APPENDIX_X, APPENDIX_Y, APPENDIX_I, APPENDIX_T, APPENDIX_PHI, APPENDIX_P_FITCH, APPENDIX_O, APPENDIX_O_LEGAL_STATUS, APPENDIX_A, APPENDIX_C, APPENDIX_D, APPENDIX_EO, APPENDIX_E, APPENDIX_ERH_ORG, APPENDIX_G, APPENDIX_J, APPENDIX_K, APPENDIX_L, APPENDIX_M, APPENDIX_MORTGAGE, APPENDIX_N
};
export {
  ERRORS,
  ERROR_CODES,
  CLIENT_STATUS,
  ERROR_DETAILS,
  NOS_TYPES,
  VALUE_CODES,
  APPENDIX,
  FORMATTABLE_VARIABLES
};