export default {
  MONGOLIAN_TUGRIK     : "MNT",
  UNITED_STATES_DOLLARS: "USD",
  RUSSIAN_RUBLE        : "RUB",
  CHINESE_YUAN_RENMINBI: "CNY",
  DEUTSCHE_MARK        : "DEM",
  BRITISH_POUND        : "GBP",
  JAPANESE_YEN         : "JPY",
  SWISS_FRANC          : "CHF",
  AUSTRIAN_SCHILLING   : "ATS",
  CANADIAN_DOLLAR      : "CAD",
  FRENCH_FRANC         : "FRF",
  HONG_KONG_DOLLAR     : "HKD",
  EUROPIAN_EURO        : "EUR",
  ITALIAN_LIRA         : "ITL",
  SOUTH_KOREAN_WON     : "KRW",
  THAI_BAHT            : "THB",
  KAZAKHSTANI_TENGE    : "KZT",
  BULGARIAN_LEV        : "BGL",
  NORTH_KOREAN_WON     : "KPW",
  AUSTRALIAN_DOLLAR    : "AUD",
  DANISH_KRONE         : "DKK",
  SWEDISH_KRONA        : "SEK",
  BELGIUM_FRANC        : "BEF",
  FINLAND_MARKKA       : "FIM",
  INDIAN_RUPEE         : "INR",
  TAIWAN_DOLLAR        : "TWD",
  LAO_KIP              : "LAK",
  VIETNAMESE_DONG      : "VND",
  HUNGARIAN_FORINT     : "HUF",
  SINGAPORE_DOLLAR     : "SGD",
};